set nocompatible

set directory=.swp/,~/.swapfiles/,/tmp/

" Include plugins:
source ~/.vim/plugins.vim

" Setup style
set expandtab
set shiftwidth=2
set tabstop=2

" Aspect
set number

" Autocompletion on the commands
set wildmode=list:longest,list:full

" Display chars on tabs and trailing spaces -> 
set list lcs=tab:»·,trail:·

" enable mouse actions
set mouse=a

" how many spaces to keep below and under cursor
set scrolloff=8

" use system clipboard
set clipboard=unnamed

" after how many miliseconds of inactivity to write the swapfile (for backup)
set updatetime=1000

" indenting smartly
set smartindent
" regex matching
set magic

" not sure which one of these two does the job
syntax enable

" Pasting + reindentation & default pasting
nnoremap p ]p
nnoremap <c-p> p

highlight Comment cterm=underline ctermbg=black ctermfg=lightgray

" Shows your command in the bottom right corner, on normal mode
set showcmd
" By default, the <Leader> is toggled for 1s. Below I move it to 5s.
set timeoutlen=5000

" Searching
set incsearch
set hlsearch
set ignorecase
set smartcase

" Resizing splits
nnoremap <silent> <Leader>+ :exe "resize " . (winwidth(0) * 3/2)<CR>
nnoremap <silent> <Leader>- :exe "resize " . (winwidth(0) * 2/3)<CR>


" backspace over everything
" set backspace=indent,eol,start


" remap leader key. Default is \\, this is just to always remember the default
let mapleader="\\"


"map gf :edit <cfile><cr>


" status line
source ~/.vim/statusline.vim

" tab line
source ~/.vim/tabline.vim

" syntastic
source ~/.vim/syntastic.vim

" buffers
nnoremap <Leader>l :ls<CR>

" reload vimrc
nnoremap <Leader>r :source $MYVIMRC<cr>

"TODO move line up and down

nnoremap <Leader>2 :1b<CR>
nnoremap <Leader>3 :2b<CR>
nnoremap <Leader>4 :3b<CR>
nnoremap <Leader>5 :4b<CR>
nnoremap <Leader>6 :5b<CR>
nnoremap <Leader>7 :6b<CR>
nnoremap <Leader>8 :7b<CR>
nnoremap <Leader>9 :8b<CR>
nnoremap <Leader>10 :9b<CR>

" My poor attempt at opening a tab with a git diff
"map diff :tab !git difftool -- %<cr><cr>
nnoremap diff :tab Gdiff<cr>

" Terminal
nnoremap ț :terminal<cr><c-w>J<cr><c-w>:resize 20<cr>
tmap <esc><esc> <c-w>:q!<cr>

nnoremap  :Files<cr>

" comments
map  gcc

" Use new regular expression engine
set re=0

" Vimscript file settings {{{
augroup filetype_vim
  autocmd!
  autocmd FileType vim setlocal foldmethod=marker
augroup END
" }}}
