set t_Co=256

set nocompatible

set directory=.swp/,~/.swapfiles/,/tmp/

source ~/.vim/plugins.vim        " Include plugins:

" Setup style
set expandtab
set shiftwidth=2
set tabstop=2

set number        " Aspect

set wildmode=list:longest,list:full        " Autocompletion on the commands

set list lcs=tab:»·,trail:·        " Display chars on tabs and trailing spaces -> 

set mouse=a        " enable mouse actions

set scrolloff=8        " how many spaces to keep below and under cursor

set clipboard=unnamed        " use system clipboard

set updatetime=1000        " after how many miliseconds of inactivity to write the swapfile (for backup)

set smartindent        " indenting smartly

set magic        " regex matching

syntax enable        " not sure which one of these two does the job

" Pasting + reindentation & default pasting
nnoremap p ]p
nnoremap <c-p> p

highlight Comment ctermbg=black ctermfg=lightgray
" highlight Comment cterm=underline ctermbg=black ctermfg=lightgray

set showcmd        " Shows your command in the bottom right corner, on normal mode
set timeoutlen=5000        " By default, the <Leader> is toggled for 1s. Below I move it to 5s.

" Searching
set incsearch
set hlsearch
set ignorecase
set smartcase

" Resizing splits
nnoremap <silent> <Leader>+ :exe "resize " . (winwidth(0) * 3/2)<CR>
nnoremap <silent> <Leader>- :exe "resize " . (winwidth(0) * 2/3)<CR>


" backspace over everything
" set backspace=indent,eol,start


let mapleader="\\"        " remap leader key. Default is \\, this is just to always remember the default


"map gf :edit <cfile><cr>


source ~/.vim/statusline.vim        " status line

source ~/.vim/tabline.vim        " tab line

source ~/.vim/syntastic.vim        " syntastic

source ~/.vim/fzf.vim           " fzf

nnoremap <Leader>l :ls<CR>        " buffers

nnoremap <Leader>r :source $MYVIMRC<cr>        " reload vimrc

"TODO move line up and down


nnoremap diff :tab Gdiff<cr>        " Open a tab with a git diff

" Terminal
nnoremap ț :let $VIM_DIR=expand('%:p:h')<cr>:terminal<cr>cd $VIM_DIR<CR><c-w>J<cr><c-w>:resize 20<cr>
tmap <esc><esc> <c-w>:q!<cr>

nnoremap  :GFiles<cr>

map  gcc        " comments

set re=0        " Use new regular expression engine

autocmd FileType xml,html set omnifunc=htmlcomplete#CompleteTags
autocmd FileType xml,html inoremap </ </<C-x><C-o>

autocmd BufWritePre *.js,*.vim,*.cpp :normal gg=G``        " reindent right before save, and come back to position

nmap ' `        " recursive map ' to ` so that jumps to mark are on the right column, not just the right line


" Always open new files in new tabs
" autocmd VimEnter * tab all
" autocmd BufAdd * exe 'tablast | tabe "' . expand( "<afile") .'"'


" if &term =~ '^screen'
"     " tmux will send xterm-style keys when its xterm-keys option is on
"     execute "set <xUp>=\e[1;*A"
"     execute "set <xDown>=\e[1;*B"
"     execute "set <xRight>=\e[1;*C"
"     execute "set <xLeft>=\e[1;*D"
" endif
